markdownSlides:
#  image: busybox:latest
  stage: deploy
  script:
    - echo "copy images..."
    - cp slides/*.png slides/*.jpg /var/www/courses.fmsoft.cn/the-basic-computer-software-methods/assets -f
    - echo "copy HTML files..."
    - cp slides/*.html /var/www/courses.fmsoft.cn/the-basic-computer-software-methods/ -f
    - echo "copy markdown files..."
    - cp slides/*.md /var/www/courses.fmsoft.cn/the-basic-computer-software-methods/gitlab/ -f
    - echo "done"
  only:
    refs:
      - main
    changes:
      - slides/*

